# Generated by Django 5.2.3 on 2025-06-10 15:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kamar', models.CharField(help_text="Nomor atau kode unik kamar, misal: 'A01' atau 'B07'", max_length=20, unique=True)),
                ('lantai', models.CharField(help_text="Posisi lantai, misal: 'Lantai 1' atau 'Bawah'", max_length=20)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('harga_per_bulan', models.DecimalField(decimal_places=2, default=700000.0, max_digits=10)),
                ('status_ketersediaan', models.CharField(choices=[('tersedia', 'Tersedia'), ('terisi', 'Terisi'), ('perbaikan', 'Dalam Perbaikan')], default='tersedia', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daftar Kamar',
            },
        ),
        migrations.CreateModel(
            name='Penyewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('nomor_telepon', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('tanggal_mulai_sewa', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kamar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penyewa_saat_ini', to='core.kamar')),
            ],
            options={
                'verbose_name_plural': 'Daftar Penyewa',
            },
        ),
    ]
