# Generated by Django 5.2.3 on 2025-06-10 15:17

from django.db import migrations


def populate_initial_data(apps, schema_editor):
    """
    Fungsi ini akan dijalankan untuk mengisi database dengan data awal.
    """
    Kamar = apps.get_model('core', 'Kamar')
    Penyewa = apps.get_model('core', 'Penyewa')

    # Membuat 14 kamar: 7 di Lantai Bawah dan 7 di Lantai Atas
    kamar_batch = []
    
    # Kamar Lantai Bawah (B01-B07)
    for i in range(1, 8):
        kamar_batch.append(
            Kamar(nomor_kamar=f"B{i:02d}", lantai="Lantai Bawah", harga_per_bulan=700000.00, status_ketersediaan='tersedia')
        )
        
    # Kamar Lantai Atas (A01-A07)
    for i in range(1, 8):
        kamar_batch.append(
            Kamar(nomor_kamar=f"A{i:02d}", lantai="Lantai Atas", harga_per_bulan=700000.00, status_ketersediaan='tersedia')
        )
        
    Kamar.objects.bulk_create(kamar_batch)

    # Menandai beberapa kamar sebagai 'terisi' dan menambahkan data penyewa dummy
    # Daftar kamar yang akan diisi beserta data penyewanya
    kamar_terisi_info = [
        {'nomor': 'B01', 'nama': 'Budi Santoso', 'telepon': '081234560001'},
        {'nomor': 'B03', 'nama': 'Citra Wijaya', 'telepon': '081234560002'},
        {'nomor': 'B04', 'nama': 'Agus Permana', 'telepon': '081234560003'},
        {'nomor': 'B06', 'nama': 'Dewi Lestari', 'telepon': '081234560004'},
        {'nomor': 'A02', 'nama': 'Eko Prasetyo', 'telepon': '081234560005'},
        {'nomor': 'A05', 'nama': 'Fitriani', 'telepon': '081234560006'},
        {'nomor': 'A07', 'nama': 'Gita Wulandari', 'telepon': '081234560007'},
    ]

    for info in kamar_terisi_info:
        try:
            # Cari kamar berdasarkan nomornya
            kamar_untuk_diisi = Kamar.objects.get(nomor_kamar=info['nomor'])
            
            # Buat data penyewa baru
            penyewa_baru = Penyewa.objects.create(
                nama_lengkap=info['nama'],
                nomor_telepon=info['telepon'],
                kamar=kamar_untuk_diisi # Hubungkan penyewa dengan kamarnya
            )
            
            # Update status kamar menjadi 'terisi'
            kamar_untuk_diisi.status_ketersediaan = 'terisi'
            kamar_untuk_diisi.save()
            
        except Kamar.DoesNotExist:
            # Lewati jika karena suatu hal kamar tidak ditemukan
            print(f"Peringatan: Kamar dengan nomor {info['nomor']} tidak ditemukan. Data penyewa tidak dibuat.")
            pass


class Migration(migrations.Migration):

    dependencies = [
        # Pastikan nama file ini sesuai dengan file migration pertama Anda
        # Biasanya bernama '0001_initial'.
        ('core', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
