# Generated by Django 5.2.3 on 2025-06-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamar',
            name='foto_kamar',
            field=models.ImageField(blank=True, help_text='Unggah foto utama kamar', null=True, upload_to='kamar_photos/'),
        ),
    ]
